# Stage 1
FROM node:12.14.0-alpine as builder
WORKDIR /app
EXPOSE 82

COPY package.json ./
COPY package-lock.json ./
RUN npm install

COPY . ./
RUN npm run build

# Stage 2
FROM nginx:1.19-alpine AS server
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build /usr/share/nginx/html